### ISSUE TITLE
The application could not be installed: INSTALL_FAILED_MISSING_SHARED_LIBRARY

### ISSUE THREAD

**Issue by TheKrushik** [datalogic/datalogic-android-sdk#12]
I have problem with add uses-library in Manifest.

After add this strings:
```
        <uses-library
            android:name="com.datalogic.device"
            android:required="true" />
```

i am getting the following installation error:

```
02/25 17:59:53: Launching 'app' on Nexus 10 API 29.
Installation did not succeed.
The application could not be installed: INSTALL_FAILED_MISSING_SHARED_LIBRARY

List of apks:
[0] 'D:\Dev\AndroidProject\Work\IKapp\app\build\outputs\apk\debug\myapp.apk'
Installation failed due to: 'null'
Retry
```

**Comment by jobhh** [comment]
Did you run the application on a Datalogic device?
It seems to be a Nexus 10 API 29 ;)

**Comment by TheKrushik** [comment]
> Did you run the application on a Datalogic device?
> It seems to be a Nexus 10 API 29 ;)

Device Nexus 10 API 29, bat i have USB scanner Datalogic Magellan 800i
I attached its scanner to the device. He personally scans in EditText, but I need to subscribe to scan events in Brodcast or Service

PS: sorry for my English

**Comment by codybrookshear** [comment]
Hi @TheKrushik,

As @jobhh alluded to, the Datalogic Android SDK is only for Datalogic mobile devices running Android that have built-in scanners (Memor 10, Memor 1, Memor 20, Joya Touch A6, Skorpio X5, DL-Axist, Skorpio X4).

In order to control a Magellan, I don't believe there are any Android drivers available (I wish there were!). It's not my area of expertise, but I believe you would need a library that implements oPOS or JavaPOS on Android for this purpose.

And your English is just fine! no worries :)

Sorry I couldn't offer any more guidance than that.

Cody
