### ISSUE TITLE
No way to detect GS1 DataMatrix and GS1 QR Code

### ISSUE THREAD

**Issue by TaylanUB** [datalogic/datalogic-android-sdk#14]
GS1 specifies special Data Matrix and QR Code types that carry GS1 keys and attributes, analogous to GS1-128.

https://www.gs1.org/docs/barcodes/GS1_Barcodes_Fact_Sheet-GS1_2D_symbols.pdf

These are valid standard Data Matrix and QR Codes, containing additional information that identifies them as being of the GS1 subtype. Analogous to Code 128 and GS1-128.

Currently, with this SDK, there seems to be no way to tell apart a regular Data Matrix / QR Code from a GS1 Data Matrix / QR Code.

I think the `BarcodeID` enum should contain `GS1_DATAMATRIX` and `GS1_QRCODE` values to tell these apart, just like it contains separate `CODE128` and `GS1_128` values to tell apart a regular Code 128 barcode from a GS1-128 barcode.

Note that this would break backwards compatibility, because some applications may rely on the `BarcodeID` being reported as `DATAMATRIX` or `QRCODE` even when they are of the GS1 subtype. (This is currently what the SDK does.) I'm not sure if there's a good way to do it without breaking backwards compatibility.

**Comment by codybrookshear** [comment]
Hi @TaylanUB 

 Regarding GS1 DataMatrix, we will be providing this capability in an upcoming Skorpio X5 firmware build first, and starting from SDK v1.28 in other devices thereafter. GS1 QR Code is planned for SDK v1.29. Likely Memor 10 will be first device including this feature and SDK v1.29, otherwise it will be in a subsequent Skorpio X5 release.
In both cases, GS1 DataMatrix and GS1 QR Code configuration will be compatible with the previous Scanner configurations of customers.

Cody
