### ISSUE TITLE
Can this SDK be used for USB connected Datalogic scale?

### ISSUE THREAD

**Issue by bus710** [datalogic/datalogic-android-sdk#6]
To whom it may concern,

I am currently working with Magellan 9800i scanner/scale device and it should be used for Android retail app/device. The connection is USB but this SDK seems like it is designed for Datalogic's handheld devices so that I am not sure if I can use this for my case.

Any guide would be appreciated.
Thanks,

**Comment by codybrookshear** [comment]
Hi,
Unfortunately, no, this SDK can't be used to talk to a Magellan 9800i. This SDK is only for our mobile Android devices (phone-like devices with a built-in scanner).

I think your starting point for development would be here with JavaPos and oPos. (Click "Utilities" link)
https://www.datalogic.com/eng/retail/fixed-retail-scanners/magellan-9800i-pd-600.html

This link could be helpful:
https://stackoverflow.com/questions/21800932/communicating-with-serial-usb-device-over-android

There are requests for such a SDK that we have received, but so far haven't had the time to implement one.

Cody

**Comment by bus710** [comment]
I should not write something in a closed ticket but just want to thank for your clarification.
Stay healthy and safe,

**Comment by codybrookshear** [comment]
👍

**Comment by SomethingNice2016** [comment]
I'm currently having the same problem. Please tell me if you managed to find a solution in the end?

**Comment by juliesaia-vendora** [comment]
Anyone in this thread have success connecting a Magellan to Android? I have it working on Windows/Mac, but any time I try to read from the serial port I get no data.

**Comment by pmar0** [comment]
The effort is appreciate, but the above recommendation doesn't work (JavaPOS is Windows/Linux-based) and DataLogic effectively refuses to support Android devices, so I wouldn't put too much stock into a solution here.

I called and spoke to their IT who said they haven't received enough requests, which I find odd considering there's been requests since 4yr ago; but that could just be generic "I don't have control over this" type stuff. Due to such, I thought I'd save others the time by posting here, as this is the most common thing to come up when searching for a solution here.

The stack overflow post above points towards some potentially useful open source stuff (one library of which is maintained, I believe, but I've yet to experiment), but it's not ideal for commercial applications since it's not really supported by the manufacturer themselves.

If y'all are looking for scale scanners that support Android dev, check out a company like Zebra.

**Comment by chenguocan** [comment]
> Anyone in this thread have success connecting a Magellan to Android? I have it working on Windows/Mac, but any time I try to read from the serial port I get no data.

Hello, I am currently receiving calls and scanner. May I ask how you deal with them on Windows and Mac?
