### ISSUE TITLE
Missing library INSTALL_FAILED_MISSING_SHARED_LIBRARY

### ISSUE THREAD

**Issue by PuntusovAleksandr** [datalogic/datalogic-android-sdk#8]
i trying to use datalogic-android-sdk in my app/ But always have error The application could not be installed: INSTALL_FAILED_MISSING_SHARED_LIBRARY
I am getting the following error in adb

device - Datalogic QD2430(QR)

can help me anybody?
maybe will me use other library?

**Comment by jobhh** [comment]
First question: Is the device you're installing on supported by the Datalogic SDK?

Other questions: Did you add one (or both) of the entries to your AndroidManifest.xml file?

```
        <uses-library
            android:name="com.datalogic.device"
            android:required="true" />

        <uses-library
            android:name="com.datalogic.extension.selfshopping"
            android:required="true" />
```

And something along these lines in your build.gradle file? (there are probably newer versions)
```
    datalogicImplementation 'com.github.datalogic:datalogic-android-sdk:1.20'
    datalogicImplementation 'com.github.datalogic:datalogic-android-sdk-selfshopping:v1.8b'
```

**Comment by codybrookshear** [comment]
Hi @PuntusovAleksandr. The advice @jobhh provided was good advice. I hope that helped you figure out what the problem was. 

It's strange that adb reports an error for `Datalogic QD2430(QR)`. That would appear to be related to a [QuickScan device](https://www.datalogic.com/eng/retail-other-solutions/hand-held-scanners/quickscan-i-qd2400-pd-612.html) rather than a mobile computer (like the Memor 20, Memor 10, Memor 1, Joya Touch A6, Skorpio X4 or DL-Axist).

Cody
